routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/login', 'Auth\LoginController@login');
Route::post('/logout', 'Auth\LoginController@logout')->name('logout');

Route::get('/register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('/register', 'Auth\RegisterController@register')->name('logout');



Route::get('/home', function() {
	    return view('home');
})->name('home')->middleware('auth');//главная

//Route::resource('calendar', 'CalendarController')->middleware('auth');
//Route::post('calendarevent', 'CalendarController@create_event')->name('calendar.create_event');
Route::get('calendarview', 'CalendarController@view')->name('calendar.view')->middleware('auth');
Route::get('calendar', 'CalendarController@index')->middleware('auth');
Route::post('calendar', 'CalendarController@store')->name('calendar.store')->middleware('auth');
/*
Route::get('test', function()
{
	event(
		new App\Events\CalendarEvent(['massage' => 'data'])
	);
});

*/

Route::middleware('auth', 'role:Administrator,Manager')->group(function () {
	Route::resource('calendar', 'CalendarController');//календарь
	Route::post('calendar', 'CalendarController@create');
	Route::patch('/calendar/{calendar}', 'CalendarController@update');
});


Route::middleware('auth', 'role:Administrator')->group(function () {
	Route::resource('statistics', 'StatisticsController');
	Route::resource('users', 'UserController');
	Route::resource('calendar', 'CalendarController');//календарь
	Route::post('statisticsview', 'StatisticsController@view')->name('statistics.storeCount');
	Route::get('/datatables', 'UserController@data')->name('db.data');//таблица пользователей
	
});


Route::middleware('auth')->group(function () {
	Route::resource('calendar', 'CalendarController');//календарь
});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laratrust\Traits\LaratrustUserTrait;
use Illuminate\Support\Facades\Hash;

class User extends Authenticatable
{
    use LaratrustUserTrait;
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    public function calendar()
    {
        return $this->belongsTo('App\Calendar');
    }
    protected $fillable = [
        'name', 'email', 'password'
    ];
    public function setPasswordAttribute($password)
    {
        $this->attributes['password'] = bcrypt($password);
        $this->attributes['hash'] = Hash::make($password);
    }
    /*
    public function setHashAttribute($hash)
    {
        $this->attributes['hash'] = Hash::make($hash);
    }*/


    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    /*protected $hidden = [
        'password', 'remember_token',
    ];*/

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    /*protected $casts = [
        'email_verified_at' => 'datetime',
    ];*/
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;
//use Illuminate\Support\Facades\DB;
use App\User;
use App\Role;
use App\Role_user;
use Illuminate\Http\Request;
use App\Http\Requests\UserRequest;
use Yajra\Datatables\Datatables;
use App\Http\Requests\UserUpdateRequest;
class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {   
        //dd($user);
        
        return view('users.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function data()
    {   
            return Datatables::of(User::query())
            ->addColumn('edit', function($edit){
                $edit = $edit->id;
                return view('plugins.edit_button', compact('edit'));
            })
            ->addColumn('delete', function($delete){
                $delete = $delete->id;
                return view('plugins.delete_button', compact('delete'));
            })
            ->rawColumns(['edit','delete'])
            ->make(true);
    }
    public function create()
    {
        $roles = Role::all();
        return view('users.create', compact('roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UserRequest $request)
    {   
        //dd($request->role);
        
        $user = User::create($request->all());
        $user->attachRole($request->role);
        flash('Пользователь создан')->success();
        return redirect()->route('users.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    //public function edit(User $user)
    public function edit(User $user)
    {
        return view('users.edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(User $user, UserUpdateRequest $request)
    {
       // dd($user);
        flash('Данные обновленны')->success();
        $user->update($request->all());
        //return $user;
        return redirect()->route('users.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {

        $user->delete();
        return 'Пользователь удален';
    }
}

resources/views/users/create.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE')

@section('content_header')

@stop

@section('content')

@foreach ($errors->all() as $error)
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        {{ $error }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
@endforeach
<div class="box box-primary p-2">
    <h3 class="box-title">Создание пользователя</h3>
    <form action="{{ route('users.store') }}" method="post">
        <input type="hidden" name="_token" value="{{ csrf_token() }}">
        <div class="form-group">
            <label>Имя</label>
            <input type="text" name="name" class="form-control " value="{{ old('name') }}" placeholder="Имя" autofocus="">
        </div>
         <div class="form-group">
            <label>Email</label>
            <input type="email" name="email" class="form-control " value="{{ old('email') }}" placeholder="Email">
        </div>

         <div class="form-group">
            <label>Пароль</label>
            <input type="password" name="password" class="form-control" placeholder="Пароль">
        </div>
        <div class="form-group">
            <label>Роль</label>
            <select name="role" class="custom-select" required>
                @foreach($roles as $role)
                    <option value="{{ $role->id }}">{{ $role->name }}</option>
                @endforeach
            </select>
            
        </div>
        <button type="submit" class="btn btn-primary">
            Регистрация
        </button>
    </form>
</div>
@stop

resources/views/users/edit.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE')

@section('content_header')

@stop

@section('content')
@foreach ($errors->all() as $error)
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        {{ $error }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
@endforeach
<div class="box box-primary p-2">
    <h3 class="box-title">Редактирование пользователя</h3>
    <form action="{{ route('users.update', $user->id) }}" method="POST">
        <input type="hidden" name="_method" value="PATCH">
        <input type="hidden" name="_token" value="{{ csrf_token() }}">
        <div class="form-group">
            <label>Имя</label>
            <input type="text" name="name" class="form-control" value="{{ $user->name }}" placeholder="Full name" autofocus="">
        </div>
        <div class="form-group">
            <label>Email</label>
            <input type="email" name="email" class="form-control" value="{{ $user->email }}" placeholder="Email">
        </div>
        <button type="submit" class="btn btn-primary">
            Обновить
        </button>
    </form>
</div>
@stop

resources/views/users/index.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE')

@section('content_header')
    
@stop

@section('content')
    @include('flash::message')
    <div class="message"></div>
    <div class="box box-primary p-2">
        <h3 class="box-title">Список пользователей</h3>
        <meta name="csrf-token" content="{{ csrf_token() }}">
        <table id="testTable" class="table table-bordered table-striped dataTable" style="width:100%">
            <thead>
                <tr role="row">
                    <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending" style="width: 361px;">id</th>
                    <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending" style="width: 361px;">Имя</th>
                    <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending" style="width: 361px;">Email</th>
                    <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending" style="width: 361px;">Редактировать</th>
                    <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending" style="width: 361px;">Удалить</th>
                    
                </tr>
            </thead>
        </table>
    </div>
    <script>
        $('div.alert').not('.alert-important').delay(3000).fadeOut(350);
        var table = $('#testTable').DataTable({
            processing: true,
            serverSide: true,
            ajax: '{!! route('db.data') !!}',
            columns: [
                { data: 'id', name: 'id' },
                { data: 'name', name: 'name' },
                { data: 'email', name: 'email' },
                { data: 'edit', name: 'edit' },
                { data: 'delete', name: 'delete' }
            ]
        });
        function del(url) {
                //console.log(url)
                $.ajaxSetup({
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    }
                });
                
                $.ajax({
                    type: 'DELETE',
                    url: url,
                    success: function(data) {
                        table.ajax.reload();
                        $('.message').append("<div class='alert alert-primary' role='alert'>" + data + "<button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button></div>")
                    }
                })
                
            
        }
    </script>
@stop