routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/login', 'Auth\LoginController@login');
Route::post('/logout', 'Auth\LoginController@logout')->name('logout');

Route::get('/register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('/register', 'Auth\RegisterController@register')->name('logout');



Route::get('/home', function() {
	    return view('home');
})->name('home')->middleware('auth');//главная

//Route::resource('calendar', 'CalendarController')->middleware('auth');
//Route::post('calendarevent', 'CalendarController@create_event')->name('calendar.create_event');
Route::get('calendarview', 'CalendarController@view')->name('calendar.view')->middleware('auth');
Route::get('calendar', 'CalendarController@index')->middleware('auth');
Route::post('calendar', 'CalendarController@store')->name('calendar.store')->middleware('auth');
/*
Route::get('test', function()
{
	event(
		new App\Events\CalendarEvent(['massage' => 'data'])
	);
});

*/

Route::middleware('auth', 'role:Administrator,Manager')->group(function () {
	Route::resource('calendar', 'CalendarController');//календарь
	Route::post('calendar', 'CalendarController@create');
	Route::patch('/calendar/{calendar}', 'CalendarController@update');
});


Route::middleware('auth', 'role:Administrator')->group(function () {
	Route::resource('statistics', 'StatisticsController');
	Route::resource('users', 'UserController');
	Route::resource('calendar', 'CalendarController');//календарь
	Route::post('statisticsview', 'StatisticsController@view')->name('statistics.storeCount');
	Route::get('/datatables', 'UserController@data')->name('db.data');//таблица пользователей
	
});


Route::middleware('auth')->group(function () {
	Route::resource('calendar', 'CalendarController');//календарь
});

app/Http/Controllers/StatisticsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Calendar;
use App\User;
use Carbon\Carbon;
use Carbon\CarbonPeriod;
class StatisticsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all();
        return view('statistics.index', compact('users'));
    }
    public function view()
    {
        $data = Calendar::all();
        return $data;
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $difference = array();
        $count = collect();
        $countMas = array();
        $dates = [];


        
        $end = Carbon::parse($request->input('end'));
        $end->setTime(23, 59, 59);
        $newEnd = $end->format('Y-m-d H:i:s', $end);
        //
        //все даты в промежутке
        $period = CarbonPeriod::create($request->input('start'), $request->input('end'));
        foreach ($period as $key => $date) 
        {
            $dates[] = $date->format('Y-m-d');
        }
        
        if($request->input('user') == 'all')
        {
            $data = Calendar::with('user')->where('status', 1)->whereBetween('updated_at', [$request->input('start'), $newEnd])->get();
        }else{
            $data = Calendar::with('user')->where('status', 1)->where('user_id', $request->input('user'))->whereBetween('updated_at', [$request->input('start'), $newEnd])->get();
        }
        $data->map(function($item, $key)
        {
            $item['difference'] = [];
        });

        foreach ($data as $key => $value)
        {
            foreach ($dates as $key2 => $value2)
            {
                $difference[$key2] = 0;
                $countMas[$value->user->id][$value2] = 0;
                if($value->staus_date == $value2)
                {
                    $difference[$key2] = Carbon::parse($value->start)->floatDiffInHours($value->updated_at);
                }
            }
            $value->difference = $difference;    
        }

        foreach ($data as $key => $value) 
        {
            foreach ($dates as $key2 => $value2) 
            {
                if($value->staus_date == $value2)
                {
                    $countMas[$value->user->id][$value2] += 1;
                    $countMas[$value->user->id]['name'] = $value->user->name;
                }
            }
            $count = $countMas;
        }
        return [
            'dates' => $dates,
            'data' => $data,
            'count' => $count
        ];
    }
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/statistics/index.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE')

@section('content_header')
    
@stop

@section('content')
<div class="container-floid row">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.bundle.min.js" integrity="sha256-TQq84xX6vkwR0Qs1qH5ADkP+MvH0W+9E7TdHJsoIQiM=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js" integrity="sha256-R4pqcOYV8lt7snxMQO/HSbVCFRPMdrhAFMH+vr9giYI=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.css" integrity="sha256-aa0xaJgmK/X74WM224KMQeNQC2xYKwlAt08oZqjeF0E=" crossorigin="anonymous" />
    
    <div class="col-3 box box-primary p-2 m-1">
        <label>Дата начала</label>
        <input class="form-control" id="statistics_start" type="date" name="start"><br>
        <label>Дата конца</label>
        <input class="form-control" id="statistics_end" type="date" name="end"><br>
        <label>Пользователь</label>
        <select id="select-user" name="role" class="custom-select" required>
            <option value="all">Все</option>
            @foreach($users as $val)
                <option value="{{ $val->id }}">{{ $val->name }}</option>
            @endforeach
        </select>
        <button id="chartTime" type="submit" class="btn btn-primary">Открыть</button>
    
    </div>
    <div class="col-4 box box-primary p-2 m-1">
        <h3 class="box-title">Статистика(События/Часы)</h3>
        <canvas class="canvas" id="myChartEventTime" width="400" height="400"></canvas>
    </div>
    <div class="col-4 box box-primary p-2 m-1">
        <h3 class="box-title">Статистика(События/кол-во)</h3>
        <canvas class="canvas" id="myChartEventCount" width="400" height="400"></canvas>
    </div>
    <script>
        $(function() {
            $('#chartTime').click(function() {
                var color = Chart.helpers.color;

                function generateColor() {
                    return '#' + Math.floor(Math.random()*16777215).toString(16) + '99'
                }

                let start = $('#statistics_start').val()
                let end = $('#statistics_end').val()
                let user = $('#select-user').val()
                console.log(start + " - " + end)
                $.ajaxSetup({
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    }
                });
                $.ajax({
                    type: 'post',
                    url: '{{ route('statistics.store') }}',
                    data: {start: start, end: end, user: user},
                    success: function(req) {
                        myChartEventTime.data.labels.splice(0,myChartEventTime.data.labels.length); 
                        myChartEventTime.data.datasets.splice(0,myChartEventTime.data.datasets.length);
                        for(i in req.dates){// Даты
                            myChartEventTime.data.labels.push(req.dates[i])
                        }
                        for(i in req.data){    
                            let newDataset = {
                                label: '[' + req.data[i].user.name + ']' + req.data[i].title,
                                backgroundColor: generateColor(),
                                borderColor: generateColor(),
                                data: req.data[i].difference,
                                fill: false,
                                border: 3
                            }
                            myChartEventTime.data.datasets.push(newDataset);
                        }
                        window.myChartEventTime.update();
                        //2
                        myChartEventCount.data.labels.splice(0,myChartEventCount.data.labels.length); 
                        myChartEventCount.data.datasets.splice(0,myChartEventCount.data.datasets.length);
                        for(i in req.dates){// Даты
                            myChartEventCount.data.labels.push(req.dates[i])
                        }
                        let arr = [];
                        $.each(req.count, function(index, value) {                            
                            $.each(value, function(index2, value2){                                
                                arr.push(value2)                                
                            })
                            var size = Object.keys(req.dates).length;
                            arr.splice(-1,1)
                            let newDataset = {
                                label: value.name,
                                backgroundColor: generateColor(),
                                borderColor: generateColor(),
                                data: arr,
                                fill: false,
                                border: 3
                            }
                            myChartEventCount.data.datasets.push(newDataset);
                            arr = []; 
                        })
                        window.myChartEventCount.update();

                        
                    }
                })

                
            })
        })




        var ctx = document.getElementById('myChartEventTime');
        var myChartEventTime = new Chart(ctx, {
            type: 'bar',
            data: {
                labels: [],
                datasets: []
            },
            options: {
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero: true
                        }
                    }]
                }
            }
        });

        var ctx = document.getElementById('myChartEventCount');
        var myChartEventCount = new Chart(ctx, {
            type: 'bar',
            data: {
                labels: [],
                datasets: []
            },
            options: {
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero: true
                        }
                    }]
                }
            }
        });
                 


            
    </script>
</div>
@stop